[package]
name = "robotics"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "Rust implementation of robotics algorithms"
authors = [ "Jean-Gabriel Simard <jeangab23@gmail.com>" ]
repository = "https://github.com/jgsimard/RustRobotics"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32"}
# not used at the moment
# pyo3 = { version = "0.18", features = ["extension-module"] }
# numpy = "0.18" # for python port

[dev-dependencies]
rand = "0.8"
rand_distr = "0.4"
plotters = "0.3"


[lib]
name = "robotics"
crate-type = ["cdylib", "lib"] # cdylib=python, lib=rust

[[example]]
name = "ekf"
path = "examples/localization/extended_kalman_filter.rs"


[[example]]
name = "ukf"
path = "examples/localization/unscented_kalman_filter.rs"

