[package]
name = "robotics"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Rust implementation of robotics algorithms"
authors = [ "Jean-Gabriel Simard <jeangab23@gmail.com>" ]
repository = "https://github.com/jgsimard/RustRobotics"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
nalgebra = { version = "0.32", features = ["rand"] }
numpy = "0.18"
rand = "0.8"
rand_distr = "0.4"
plotters = "0.3"


[lib]
name = "robotics"
crate-type = ["cdylib", "lib"] # cdylib=python, lib=rust

[[example]]
name = "ekf"
path = "examples/localization/extended_kalman_filter.rs"


[[example]]
name = "pf"
path = "examples/localization/particle_filter.rs"

